# Generated by Django 2.2.3 on 2020-07-26 17:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email field', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone field', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Address field', max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter account', max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook account', max_length=300, null=True)),
                ('linkedIn', models.CharField(blank=True, help_text='LinkedId account', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name field', max_length=300, null=True)),
                ('logo_url', models.CharField(blank=True, help_text='Image url', max_length=150, null=True)),
                ('logo_public_id', models.CharField(blank=True, help_text='Image public_id', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name field', max_length=300)),
                ('email', models.EmailField(help_text='Email field', max_length=254)),
                ('topic', models.CharField(help_text='Phone field', max_length=300)),
                ('message', models.TextField(blank=True, help_text='Message', null=True)),
                ('status', django_mysql.models.EnumField(choices=[('UNREAD', 'This message has not been read'), ('READ', 'This message has been read')], default='UNREAD', help_text='Message status')),
            ],
        ),
    ]
