# Generated by Django 2.2.3 on 2020-07-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='about',
            field=models.TextField(blank=True, help_text='About us', null=True),
        ),
    ]
