# Generated by Django 2.2.3 on 2020-01-21 11:59
from django.db import migrations


def create_contact_info(apps, schema_editor):
    contact_info_model = apps.get_model('contact_info', 'ContactInfo')
    contact_info_model.objects.create(id=1, email="orbita@orbita.co.cu", phone="+5372728992",
                                      address='Calle 21 #21803, e/ 218 y 218A, Reparto Atabey, Playa. La Habana')


class Migration(migrations.Migration):
    dependencies = [
        ('contact_info', '0002_contactinfo_about'),
    ]

    operations = [
        migrations.RunPython(create_contact_info)
    ]
