# Generated by Django 2.2.3 on 2020-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0003_create_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='pdf_public_id',
            field=models.CharField(blank=True, help_text='Pdf public_id', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='pdf_url',
            field=models.CharField(blank=True, help_text='Pdf url', max_length=150, null=True),
        ),
    ]
