# Generated by Django 2.2.3 on 2020-07-13 20:47

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(help_text='Category spanish title', max_length=63)),
                ('title_en', models.CharField(help_text='Category english title', max_length=63)),
                ('description_es', models.CharField(blank=True, help_text='Category spanish description', max_length=250, null=True)),
                ('description_en', models.CharField(blank=True, help_text='Category english description', max_length=250, null=True)),
                ('slug_es', models.SlugField(help_text='Category spanish slug', max_length=65, unique=True)),
                ('slug_en', models.SlugField(help_text='Category english slug', max_length=65, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order of visualization')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(help_text='Category parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('on_sale', models.BooleanField(default=True, help_text='Offer is on sale')),
                ('title_es', models.CharField(help_text='Offer title', max_length=120)),
                ('title_en', models.CharField(help_text='Offer title', max_length=120)),
                ('description_es', models.TextField(blank=True, help_text='Offer description', null=True)),
                ('description_en', models.TextField(blank=True, help_text='Offer description', null=True)),
                ('price', models.FloatField(blank=True, help_text='Offer price', null=True)),
                ('currency', django_mysql.models.EnumField(blank=True, choices=[('CUC', 'Cuban Convertible Peso'), ('USD', 'US Dollar'), ('CUP', 'Cuban Peso')], default='CUC', help_text='Currency type', null=True)),
                ('slug_es', models.SlugField(default=None, help_text='Offer slug', max_length=150, null=True, unique=True)),
                ('slug_en', models.SlugField(default=None, help_text='Offer slug', max_length=150, null=True, unique=True)),
                ('permalink_es', models.CharField(default=None, help_text='Offer permalink', max_length=200, null=True, unique=True)),
                ('permalink_en', models.CharField(default=None, help_text='Offer permalink', max_length=200, null=True, unique=True)),
                ('short_description_es', models.CharField(blank=True, help_text='Offer short description', max_length=100, null=True)),
                ('short_description_en', models.CharField(blank=True, help_text='Offer short description', max_length=100, null=True)),
                ('subcategory', models.ForeignKey(help_text='Related category', on_delete=django.db.models.deletion.CASCADE, to='offers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Image url', max_length=150)),
                ('public_id', models.CharField(help_text='Image public_id', max_length=150)),
                ('offer', models.ForeignKey(help_text='Related offer', on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
        ),
    ]
