# Generated by Django 2.2.3 on 2020-07-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(help_text='Material title', max_length=120)),
                ('title_en', models.CharField(help_text='Material title', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OffersMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(help_text='Related material', on_delete=django.db.models.deletion.CASCADE, to='offers.Material')),
                ('offer', models.ForeignKey(help_text='Related offer', on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
        ),
    ]
