# Generated by Django 2.2.3 on 2020-07-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_material_offersmaterial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('title_es', 'title_en')},
        ),
        migrations.AlterUniqueTogether(
            name='offersmaterial',
            unique_together={('offer', 'material')},
        ),
    ]
