# Generated by Django 2.2.3 on 2020-08-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20200726_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='recommended',
            field=models.BooleanField(default=False, help_text='Offer is recommended'),
        ),
    ]
